### ISSUE TITLE
Updating a repository should not create the commit message "initial commit after generate"

### ISSUE THREAD

**Issue by izerecord** [abes140377/yade-generator-cli#6]
Maybe it should not even create a commit in the first place.

**Comment by abes140377** [comment]
Solution: Do not commit the generated files to git. Let the user decide 
if and when he wants to commit. Makes it easier to rolback changes from 
subsequent runs if something is overwritten accidentally.

**Comment by abes140377** [comment]
Fixed in commit bf49c8f23be737756cd78667810352ab358135be on develop branch
